### ISSUE TITLE
兄弟，你这根本就pod不下来呀，赶紧修复下

### ISSUE THREAD

**Issue by q351941406** [Phelthas/Demo_ButtonImageTitleEdgeInsets#1]
[!] Unable to satisfy the following requirements:
- `LXMButtonImagePosition (= 1.1.0)` required by `Podfile`

Specs satisfying the `LXMButtonImagePosition (= 1.1.0)` dependency were found, but they required a higher minimum deployment target.

我的版本是7.1～

**Comment by Phelthas** [comment]
兄弟 @q351941406 
这个是要求你project的 minimum deployment target至少是7.1（项目-target-Deployment target）；  
不是说你podfile里面写的那句 `platform :ios, '7.1'`  
不过这儿我也有问题，写个7.1这么不前不后的版本（其实是因为7.1比7.0修复了不少bug，稳定了很多），这些属性是很早很早之前就可以用的，我改一下吧

**Comment by q351941406** [comment]
我的project是7.1，但podfile是7.0，你改一下吧，统一改成7.0呀，而且最低支持版本你要写在说明里呀，不然别人都不知道

**Comment by Phelthas** [comment]
@q351941406 谢谢提醒~ 刚刚改完，最低支持已经改成5.0了，你用1.1.1版本  pod update 一下应该就可以了
